# Generated by Django 2.0 on 2017-12-09 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accuounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='khyams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('discription', models.TextField()),
                ('files_id', models.IntegerField()),
                ('slug_name', models.CharField(max_length=15)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Accuounts.users')),
            ],
        ),
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('khima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='khima.khyams')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Accuounts.users')),
            ],
        ),
    ]
